# Generated by Django 2.1.1 on 2018-09-22 08:25  # noqa: D100

from django.db import migrations

import s3direct.fields


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [("will_of_the_prophets", "0002_roll_timestamped")]

    operations = [
        migrations.AlterField(
            model_name="specialsquaretype",
            name="image",
            field=s3direct.fields.S3DirectField(),
        )
    ]
