# Generated by Django 2.1.4 on 2018-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("will_of_the_prophets", "0004_specialsquaretype_auto_move")
    ]

    operations = [
        migrations.AlterField(
            model_name="roll",
            name="number",
            field=models.PositiveIntegerField(),
        )
    ]
