# Generated by Django 2.2 on 2019-04-18 12:07  # noqa: D100

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [("will_of_the_prophets", "0004_specialsquaretype_auto_move")]

    operations = [
        migrations.AddField(
            model_name="butthole",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AddField(
            model_name="butthole",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
        migrations.AddField(
            model_name="specialsquare",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AddField(
            model_name="specialsquare",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
        migrations.AlterField(
            model_name="butthole",
            name="start_square",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="specialsquare",
            name="square",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
