name: JavaScript
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint-js:
    name: Lint JavaScript
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Setup
        run: npm ci
      - name: Lint JavaScript
        run: npx prettier --check -- "**/*.js"
