name: JSON
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint-json:
    name: Lint JSON
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Setup
        run: npm ci
      - name: Lint JSON
        run: npx prettier --check -- "*.json" "**/*.json"
