name: Python
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint-python:
    name: Lint Python Code
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Read Python version
        run: echo PYTHON_VERSION=$(cat runtime.txt | sed "s/python-//") >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      - name: Setup
        run: |
          pip install --requirement requirements.txt
      - name: Lint Python Code
        run: make lint-python
