name: SCSS
on:
  pull_request:
    branches:
      - "*"
  push:
    paths:
      - "**/*.scss"
      - ".github/workflows/scss.yaml"
      - "Makefile"

jobs:
  lint-scss:
    name: Lint SCSS
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: npm install prettier@`cat package-lock.json | jq ".dependencies.prettier.version" --raw-output`
      - name: Lint SCSS
        run: make lint-scss

  latest-scss:
    name: Test the latest SCSS was commited
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Make CSS and compare with GitHub
        run: |
          pipenv run python manage.py compilescss
          git diff --no-ext-diff --exit-code
