name: SCSS
on:
  pull_request:
    branches:
      - "*"

jobs:
  latest-scss:
    name: Test the latest SCSS was commited
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Read Python version
        run: echo PYTHON_VERSION=$(cat runtime.txt | sed "s/python-//") >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      - name: Setup
        run: |
          pip install --requirement requirements.txt
      - name: Make CSS and compare with GitHub
        run: |
          python manage.py compilescss
          git diff --no-ext-diff --exit-code
