name: YAML
on:
  pull_request:
    branches:
      - "*"

jobs:
  lint-yaml:
    name: Lint YAML
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 21
      - name: Setup
        run: npm ci
      - name: Lint YAML
        run: npx prettier --check -- "**/*.yaml"
